
#include "register/tilingdata_base.h"

namespace optiling {
BEGIN_TILING_DATA_DEF(ConvTranspose3dLogSumExpHardSwishSubtractClampMaxCustomTilingData)
  TILING_DATA_FIELD_DEF(uint32_t, totalLength);
  TILING_DATA_FIELD_DEF(uint32_t, tileLength);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(ConvTranspose3dLogSumExpHardSwishSubtractClampMaxCustom, ConvTranspose3dLogSumExpHardSwishSubtractClampMaxCustomTilingData)
}
