
#include "register/tilingdata_base.h"

namespace optiling {
BEGIN_TILING_DATA_DEF(Conv2dGroupNormTanhHardSwishResidualAddLogSumExpCustomTilingData)
  TILING_DATA_FIELD_DEF(uint32_t, totalPositions);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(Conv2dGroupNormTanhHardSwishResidualAddLogSumExpCustom, Conv2dGroupNormTanhHardSwishResidualAddLogSumExpCustomTilingData)
}
