
#include "register/tilingdata_base.h"

namespace optiling {
BEGIN_TILING_DATA_DEF(Convtranspose2dGlobalavgpoolBiasaddLogsumexpSumMultiplyCustomTilingData)
  TILING_DATA_FIELD_DEF(uint32_t, batchSize);
  TILING_DATA_FIELD_DEF(uint32_t, channels);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(Convtranspose2dGlobalavgpoolBiasaddLogsumexpSumMultiplyCustom, Convtranspose2dGlobalavgpoolBiasaddLogsumexpSumMultiplyCustomTilingData)
}
