
#include "register/tilingdata_base.h"

namespace optiling {
BEGIN_TILING_DATA_DEF(ConvDepthwise2dSquareInputAsymmetricKernelCustomTilingData)
  TILING_DATA_FIELD_DEF(uint32_t, size);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(ConvDepthwise2dSquareInputAsymmetricKernelCustom, ConvDepthwise2dSquareInputAsymmetricKernelCustomTilingData)
}
